name: Version
description: Compute version number
inputs:
  token:
    description: Token
    default: ${{ github.token }}
    required: true
runs:
  using: composite
  steps:
    - name: Version
      run: |
        url="https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git"
        version="$(${{ github.action_path }}/version.sh "${url}")"
        echo "${version}"
        echo "VERSION=${version}" >> ${GITHUB_ENV}
        echo "::set-output name=VERSION::${version}"
      shell: bash
