name: pre-commit
description: Run pre-commit hooks
runs:
  using: composite
  steps:
    - name: pre-commit
      run: |
        pip install pre-commit
        if [[ -f .pre-commit-config.yaml ]]; then
          pre-commit run -a
        else
          yq e -i 'del(.repos[] | select(.repo == "local"))' "${{ github.action_path }}/../.pre-commit-config.yaml"
          cat "${{ github.action_path }}/../.pre-commit-config.yaml"
          pre-commit run -c "${{ github.action_path }}/../.pre-commit-config.yaml" -a
        fi
      shell: bash
    - name: git diff
      if: ${{ always() }}
      run: git diff --exit-code
      shell: bash
