name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: pre-commit
        uses: ./pre-commit
      - name: Workflow Mutex
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: ./workflow-mutex
      - name: Version
        uses: ./version
        with:
          minimum_version_command: cat version.txt
      - name: Tag
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          if [[ ${VERSION} =~ ([0-9]+).([0-9]+).([0-9]+) ]]; then
            git tag -a "${BASH_REMATCH[1]}"
            git tag -a "${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
          fi
      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" gh release create "v${VERSION}" --generate-notes
          git push --tags
