name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mutex
        uses: ./workflow-mutex
      - name: sleep
        run: sleep 100
      - name: Version
        run: |
          export VERSION=$(./version.sh)
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
