name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version
        run: |
          export VERSION=$(./version.sh)
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker - Build and Push
        uses: docker/build-push-action@v3
        with:
          context: workflow-lock
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}-workflow-lock:latest
            ghcr.io/${{ github.repository }}-workflow-lock:v${{ env.VERSION }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-workflow-lock:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-workflow-lock:buildcache,mode=max
